### ISSUE TITLE
ADS1X15::getMaxVoltage()

### ISSUE THREAD

**Issue by samcontrollers** [RobTillaart/ADS1X15#12]
Dear Rob,
Thank you for set of code and thinking through all parts.

RE:  float ADS1X15::getMaxVoltage()
In different Gain values, except "0" this switch is not working properly.
Change to :
float ADS1X15::getMaxVoltage()
{
  switch (_gain)
  {
/*  case 0:  return 6.144;  // original and it is not correct
    case 1:  return 4.096;
    case 2:  return 2.048;
    case 4:  return 1.024;
    case 8:  return 0.512;
    case 16: return 0.256; */
    case ADS1X15_PGA_6_144V: return 6.144;
    case ADS1X15_PGA_4_096V: return 4.096;
    case ADS1X15_PGA_2_048V: return 2.048;
    case ADS1X15_PGA_1_024V: return 1.024;
    case ADS1X15_PGA_0_512V: return 0.512;
    case ADS1X15_PGA_0_256V: return 0.256;
  }
  return ADS1X15_INVALID_VOLTAGE;
}
And test - all work for 1115 well.

Also,  in setComparatorQueConvert
                            ^
was letter "e" instead "a"

Small and perhaps not important things.
Thank you again for work !

**Comment by RobTillaart** [comment]
Thanks for the remarks, will fix asap
