### ISSUE TITLE
Allow specifying I2C bus

### ISSUE THREAD

**Issue by MaffooClock** [RobTillaart/ADS1X15#20]
This library hardcodes the `Wire` bus, so it's impossible to use this with sensors on any other I2C bus that may be available (`Wire1`, `Wire2`, etc.).

I may see if I can handle this and submit a PR...

**Comment by RobTillaart** [comment]
Thanks for reporting, it is on my todo list, I prefer to use a similar construct in all my libs.
So it should be a bit like - https://github.com/RobTillaart/PCF8574/blob/master/PCF8574.h 

I have some time so you might expect a development stream in an hour or so.

**Comment by MaffooClock** [comment]
> I have some time so you might expect a development stream in an hour or so.

Cool!  I'd already started on it (seems pretty simple to do) since my project cannot continue without this, but I'll hold off for now since you're on it.

**Comment by RobTillaart** [comment]
develop branch is uploaded, tests are running

**Comment by MaffooClock** [comment]
Perfect!

**Comment by RobTillaart** [comment]
Which platform? (for reference)

I will merge the branch, thanks for testing!

**Comment by MaffooClock** [comment]
> Which platform? (for reference)
Teensy 4.1

**Comment by RobTillaart** [comment]
OK, if there are more issues, just let me know!
