### ISSUE TITLE
ADS1X15 Continuous Mode AND differential (0_1) & (2_3)

### ISSUE THREAD

**Issue by NovaJeff** [RobTillaart/ADS1X15#29]
Hi Rob, thanks for your libraries, I've been using many of them for years.

Is there a way to get both differential values (0_1 AND 2_3) on continuous mode?

I've been able to get.Value() on either, depending on the trigger read in setup(), but for the life of me I can't find a way to do it on both channels simultaneously...

Is there something obvious I'm missing?

Thank you Rob.

**Comment by RobTillaart** [comment]
@NovaJeff 
FYI, I created a develop branch as I saw I need to fix the build-CI and some small readme updates. 
Also added an example for continuous -differential reading. Could you test that for me?
It is not a PR yet 

See - https://github.com/RobTillaart/ADS1X15/tree/develop

**Comment by RobTillaart** [comment]
Thanx, good to hear it solves the issue. I will investigate if I can get continuous differential working, if so I'll let you know.

Until that investigation is done I keep this issue open as a reminder for me.

**Comment by RobTillaart** [comment]
0.3.2 released.
