### ISSUE TITLE
Can this be used with esp32 dev kit? (esp-wroom32 dev board)? 

### ISSUE THREAD

**Issue by AtharZafeer** [RobTillaart/ADS1X15#4]

**Comment by RobTillaart** [comment]
I have used it successfully with an ESP32  Dev Module.
Worked both in single mode and differential mode

|  ADS1115 | ESP32 | notes |
|:----:|:----:|:----|
| VCC | 5V | |
| GND | GND |  |
|SDA | SDA | pull up to +3.3V |
|SCL | SCL | pull up to +3.3V |

On my TODO list is adding a ESP32 specific **begin(sda, scl)** to allow pin selection 
I will make an issue for that,

**Comment by AtharZafeer** [comment]
Thank you!. I will try it once I get my hardware and let you know
