### ISSUE TITLE
ESP32 work on Espressif 1.04 but No on Espressif 2,07

### ISSUE THREAD

**Issue by ziojos** [RobTillaart/ADS1X15#52]
On IDE 2.04 and   Espressif 1.04 I can read 6 Channels with PlotChannels.ino 
when I install latest  Espressif 2,07 and compile the same  PlotC hannels.ino script I have no error but the SW return 0 (zero) on al channel

**Comment by RobTillaart** [comment]
@ziojos 

> I can read 6 Channels with PlotChannels.ino

- The ADS1x15 has no 6 channels but 4 
- This library has no sketch called plotChannels.ino. 
- Are you using this library????

> when I install latest Espressif 2,07 and compile the same PlotC hannels.ino script I have no error...

- Does the changelog of Espressif mention I2C changes?

**Comment by ziojos** [comment]
Sorry, I Wrote on wrong github. My problem was on a Decoder PPM that work toghetre your ADS library on a RC projiet. I Apologise for my error

**Comment by RobTillaart** [comment]
I will close the issue.
