### ISSUE TITLE
[Query] Example for continuously reading all four channels at max sps?

### ISSUE THREAD

**Issue by subhashisbhowmik** [RobTillaart/ADS1X15#55]
If I read all 4 channels at 860 SPS, it should be 215 SPS per channel, 1.2ms between requesting a conversion and the interrupt on ALRT/Ready. In single shot mode, that is not the case for me, it takes a bit more than 6ms for the interrupt to occur after I switch the channel. I'm not sure if this is expected or am I doing something wrong or the chip is faulty. I can get 1.2ms delay If I read from a single channel in Continuous mode. Is there a way to achieve this 215 (At least 200) SPS from each channel while reading all 4? Can you please provide an example if so?

Thanks!!

**Comment by RobTillaart** [comment]
Thanks for opening the issue,

See issue #49 for same question and discussion about performance of the ADS1115..

In ahort, the 860sps can be achieved under some conditions but not all. Cannot improve on current examples / code given in #49.
